In [3]:
import torch

In [6]:
A=[[1,0,1],[0,1,1],[1,1,1]]
A=torch.tensor(A,dtype=torch.int)
print(A)
f,h=A.shape
print(f)

tensor([[1, 0, 1],
        [0, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
3


In [7]:
import numpy as np
I = np.identity(n=f)
I=torch.tensor(I,dtype=torch.int)
I

tensor([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]], dtype=torch.int32)

In [8]:
M = np.concatenate((A,I),axis=1)
M=torch.tensor(M,dtype=torch.int)
print(M)

tensor([[1, 0, 1, 1, 0, 0],
        [0, 1, 1, 0, 1, 0],
        [1, 1, 1, 0, 0, 1]], dtype=torch.int32)


In [9]:
for i in range (0,f):
    pivot = M[i][i]
    row =M[i]
    M[i] = row / pivot
    for j in [k for k in range(0,f) if k!=i]:
        M[j] = M[j]-M[i]*M[j][i]
    inverse = M[:,f:]
print(inverse)

tensor([[ 0, -1,  1],
        [-1,  0,  1],
        [ 1,  1, -1]], dtype=torch.int32)
