In [1]:
import torch

In [2]:
a=[[2,1,4],[2,1,2],[3,4,3]]
a=torch.tensor(a,dtype=torch.int)
print(a)

tensor([[2, 1, 4],
        [2, 1, 2],
        [3, 4, 3]], dtype=torch.int32)


In [3]:
b=[[1,2,3],[4,5,6],[7,8,9]]
b=torch.tensor(b,dtype=torch.int)
print(b)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]], dtype=torch.int32)


In [4]:
r=[[0,0,0],[0,0,0],[0,0,0]]
r=torch.tensor(r,dtype=torch.int)
print(r)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]], dtype=torch.int32)


In [5]:
for i in range(len(a)):
    for j in range (len(b[0])):
        for k in range (len(b)):
            r[i][j]+= a[i][k]*b[k][j]
print(r)

tensor([[34, 41, 48],
        [20, 25, 30],
        [40, 50, 60]], dtype=torch.int32)
